@startuml Dock
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(PAO, "Port Authority Officer", "System user managing port authority operations")

Container_Boundary(Dockapi, "Dock API") {
    Component(DockController, "Dock Controller", "ASP.NET Core MVC Controller", "Handles HTTP requests related to Docks")
    Component(DockService, "Dock Service", ".NET 8 (ASP.NET Core)", "Business logic for Docks")
    Component(Dock, "Dock", "Domain Model", "Represents a Dock")
    Component(DockRepository, "Dock Repository", ".NET 8 (ASP.NET Core)", "Data access for Docks")
    Component(DockDbContext, "Dock DbContext", ".NET 8 (Entity Framework Core)", "EF Core DbContext for Docks")
    ComponentDb(db, "Shipping Management Database", "SQL Server", "Stores all data related to shipping management")
}


DockService -[hidden]right-> Dock
DockRepository -[hidden]right-> DockDbContext


Rel(PAO, DockController, "Sends HTTP requests", "HTTPS/JSON")
Rel(DockController, DockService, "Calls methods in", "Method Calls")
Rel(DockService, Dock, "Uses", "Domain Logic")
Rel(DockService, DockRepository, "Uses", "Method Calls")
Rel(DockRepository, DockDbContext, "Uses", "Method Calls")
Rel(DockDbContext, db, "Reads from and writes to", "EF Core/SQL")


@enduml